#Compile automatic tests and run them, outputting errors

name: Tests
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              Name: Windows VS2022,
              os: windows-latest,
              cc: gcc,
              cxx: g++,
              arch: "x64-windows",
            }
          - {
              Name: Linux GCC,
              os: ubuntu-latest,
              cc: gcc,
              cxx: g++,
              arch: "x64-linux",
            }
          - {
              Name: Linux Clang,
              os: ubuntu-latest,
              cc: clang,
              cxx: clang++,
              arch: "x64-linux",
            }
          - {
              Name: MacOS Clang,
              os: macos-latest,
              cc: clang,
              cxx: clang++,
              arch: "x64-osx",
            }
        build_type: [Release]
    env:
      buildDir: '${{ github.workspace }}\build'
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Update and install Ubuntu packages
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt install ninja-build
      - name: Log Ninja version on non-Windows platforms
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: ninja --version
      - name: Log CMake version
        shell: bash
        run: cmake --version
      - name: Generate CMake project on non-Windows platforms
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        working-directory: ${{ github.workspace }}
        run: cmake -S . -B ./build/ -G Ninja
      - name: Generate CMake project on Windows
        if: ${{ runner.os == 'Windows' }}
        shell: bash
        working-directory: ${{ github.workspace }}
        run: cmake -S . -B ./build/
      - name: Build CMake project
        shell: bash
        working-directory: ${{github.workspace}}
        run: cmake --build $GITHUB_WORKSPACE/build --config ${{ matrix.build_type }}
      - name: Run auto tests
        shell: bash
        working-directory: ${{github.workspace}}/build/test/
        run: ctest -C ${{ matrix.build_type }}
        continue-on-error: true
      - name: Process JUnit report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "**/unittests.*.xml"
          require_tests: true
          fail_on_failure: true